apiVersion: v1
kind: Pod
metadata:
  name: max-pod
spec:
  restartPolicy: Always
  containers:
  - name: max-container
    image: ubuntu
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y stress && stress --vm 1 --vm-bytes 1024M"]
