apiVersion: v1
kind: Pod
metadata:
  name: minimal-pod
spec:
  containers:
  - name: minimal-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    resources:
      limits:
        cpu: "10m"  # Ograniczenie CPU do 10 millicores
        memory: "20Mi"  # Ograniczenie pamięci do 20 megabajtów
      requests:
        cpu: "5m"  # Żądanie CPU to 5 millicores
        memory: "10Mi"  # Żądanie pamięci to 10 megabajtów
